import { Disease } from "./diseases";

// Extended disease database with 200+ conditions
export const extendedDiseases: Disease[] = [
  // CARDIOVASCULAR DISEASES
  {
    id: "heart-failure",
    name: "Heart Failure",
    category: "Cardiovascular",
    description: "A chronic condition where the heart doesn't pump blood as efficiently as it should, leading to fatigue, shortness of breath, and fluid retention.",
    symptoms: ["Shortness of breath", "Fatigue", "Swelling in legs and ankles", "Rapid heartbeat", "Persistent cough", "Reduced ability to exercise", "Sudden weight gain"],
    causes: ["Coronary artery disease", "High blood pressure", "Diabetes", "Cardiomyopathy", "Heart valve disease", "Congenital heart defects"],
    prevention: ["Control blood pressure", "Maintain healthy weight", "Regular exercise", "Don't smoke", "Limit alcohol", "Reduce stress"],
    treatment: ["ACE inhibitors", "Beta-blockers", "Diuretics", "Lifestyle changes", "Implantable devices", "Surgery in severe cases"],
    riskFactors: ["Age over 65", "History of heart attack", "Diabetes", "Obesity", "Sleep apnea"],
    whenToSeeDoctor: "Seek emergency care if you experience sudden severe shortness of breath, chest pain, or fainting."
  },
  {
    id: "atrial-fibrillation",
    name: "Atrial Fibrillation",
    category: "Cardiovascular",
    description: "An irregular and often rapid heart rate that can increase risk of stroke, heart failure, and other heart-related complications.",
    symptoms: ["Heart palpitations", "Weakness", "Fatigue", "Lightheadedness", "Shortness of breath", "Chest pain"],
    causes: ["High blood pressure", "Heart attacks", "Coronary artery disease", "Thyroid disorders", "Sleep apnea", "Excessive alcohol"],
    prevention: ["Heart-healthy diet", "Regular exercise", "Maintain healthy weight", "Limit caffeine and alcohol", "Manage stress"],
    treatment: ["Blood thinners", "Heart rate medications", "Cardioversion", "Ablation", "Pacemaker"],
    riskFactors: ["Age", "Heart disease", "High blood pressure", "Chronic conditions", "Obesity", "Family history"],
    whenToSeeDoctor: "Seek immediate help if you feel chest pain or your heart racing uncontrollably."
  },
  {
    id: "peripheral-artery-disease",
    name: "Peripheral Artery Disease",
    category: "Cardiovascular",
    description: "A circulatory condition where narrowed blood vessels reduce blood flow to the limbs, typically the legs.",
    symptoms: ["Leg pain when walking", "Leg numbness or weakness", "Coldness in lower leg or foot", "Sores that won't heal", "Shiny skin on legs", "Hair loss on legs"],
    causes: ["Atherosclerosis", "Blood vessel inflammation", "Injury to limbs", "Unusual anatomy of muscles or ligaments"],
    prevention: ["Quit smoking", "Control blood sugar", "Exercise regularly", "Eat a healthy diet", "Maintain healthy weight"],
    treatment: ["Medications for cholesterol and blood pressure", "Blood thinners", "Angioplasty", "Bypass surgery"],
    riskFactors: ["Smoking", "Diabetes", "Obesity", "High blood pressure", "High cholesterol", "Age over 50"],
    whenToSeeDoctor: "See a doctor if you have leg pain while walking or signs of poor circulation."
  },
  {
    id: "deep-vein-thrombosis",
    name: "Deep Vein Thrombosis (DVT)",
    category: "Cardiovascular",
    description: "A blood clot that forms in a deep vein, usually in the legs, which can be life-threatening if it travels to the lungs.",
    symptoms: ["Leg swelling", "Leg pain or cramping", "Red or discolored skin", "Warmth in affected leg", "Visible veins"],
    causes: ["Prolonged bed rest", "Surgery", "Injury to veins", "Pregnancy", "Birth control pills", "Obesity"],
    prevention: ["Move regularly", "Wear compression stockings", "Stay hydrated", "Maintain healthy weight", "Quit smoking"],
    treatment: ["Blood thinners", "Clot busters", "Filters", "Compression stockings"],
    riskFactors: ["Age over 60", "Prolonged sitting", "Bed rest", "Pregnancy", "Obesity", "Cancer"],
    whenToSeeDoctor: "Seek immediate care if you have sudden leg swelling with pain, especially if accompanied by shortness of breath."
  },
  {
    id: "aortic-aneurysm",
    name: "Aortic Aneurysm",
    category: "Cardiovascular",
    description: "An enlargement of the aorta that can rupture and cause life-threatening internal bleeding.",
    symptoms: ["Often no symptoms", "Deep constant pain in belly or side", "Back pain", "Pulsing near the navel"],
    causes: ["Hardening of arteries", "High blood pressure", "Blood vessel diseases", "Infection", "Trauma"],
    prevention: ["Don't smoke", "Control blood pressure", "Regular checkups", "Eat healthy", "Exercise regularly"],
    treatment: ["Watchful waiting for small aneurysms", "Blood pressure medications", "Surgery for large aneurysms"],
    riskFactors: ["Age over 65", "Tobacco use", "High blood pressure", "Family history", "Male sex"],
    whenToSeeDoctor: "Seek emergency care for sudden, intense abdominal or back pain, as this could indicate a rupture."
  },

  // RESPIRATORY DISEASES
  {
    id: "tuberculosis",
    name: "Tuberculosis",
    category: "Respiratory",
    description: "A serious infectious disease that mainly affects the lungs, caused by bacteria that spread through the air.",
    symptoms: ["Coughing for 3+ weeks", "Coughing up blood", "Chest pain", "Weight loss", "Fever", "Night sweats", "Fatigue"],
    causes: ["Mycobacterium tuberculosis bacteria", "Spread through respiratory droplets", "Close contact with infected persons"],
    prevention: ["BCG vaccination", "Good ventilation", "Avoid close contact with infected persons", "Complete treatment if infected"],
    treatment: ["Combination of antibiotics for 6-9 months", "Direct observation therapy", "Isolation if infectious"],
    riskFactors: ["HIV/AIDS", "Diabetes", "Severe kidney disease", "Cancer treatment", "Malnutrition", "Very young or old age"],
    whenToSeeDoctor: "See a doctor if you have a persistent cough, unexplained weight loss, or night sweats."
  },
  {
    id: "pulmonary-fibrosis",
    name: "Pulmonary Fibrosis",
    category: "Respiratory",
    description: "A lung disease that occurs when lung tissue becomes damaged and scarred, making it difficult to breathe.",
    symptoms: ["Shortness of breath", "Dry cough", "Fatigue", "Unexplained weight loss", "Aching muscles and joints", "Clubbing of fingers"],
    causes: ["Occupational toxins", "Radiation therapy", "Certain medications", "Medical conditions", "Often unknown (idiopathic)"],
    prevention: ["Avoid tobacco smoke", "Avoid environmental pollutants", "Treat underlying conditions", "Get vaccinated"],
    treatment: ["Medications to slow progression", "Oxygen therapy", "Pulmonary rehabilitation", "Lung transplant"],
    riskFactors: ["Age 50-70", "Smoking history", "Occupational exposure", "Cancer treatments", "Genetic factors"],
    whenToSeeDoctor: "See a doctor if you have persistent shortness of breath or a dry cough that doesn't improve."
  },
  {
    id: "sleep-apnea",
    name: "Sleep Apnea",
    category: "Respiratory",
    description: "A serious sleep disorder where breathing repeatedly stops and starts during sleep.",
    symptoms: ["Loud snoring", "Gasping for air during sleep", "Morning headache", "Difficulty staying asleep", "Excessive daytime sleepiness", "Difficulty paying attention"],
    causes: ["Obstructed airway (obstructive)", "Brain signaling issues (central)", "Excess weight", "Neck circumference", "Narrowed airway"],
    prevention: ["Maintain healthy weight", "Exercise regularly", "Avoid alcohol", "Don't smoke", "Sleep on your side"],
    treatment: ["CPAP therapy", "Oral appliances", "Surgery", "Weight loss", "Positional therapy"],
    riskFactors: ["Excess weight", "Neck circumference", "Male sex", "Older age", "Family history", "Nasal congestion"],
    whenToSeeDoctor: "See a doctor if you snore loudly, have observed breathing pauses during sleep, or experience excessive daytime drowsiness."
  },
  {
    id: "bronchiectasis",
    name: "Bronchiectasis",
    category: "Respiratory",
    description: "A chronic condition where the airways of the lungs become abnormally widened, leading to mucus buildup and recurrent infections.",
    symptoms: ["Daily cough with mucus", "Shortness of breath", "Wheezing", "Chest pain", "Coughing up blood", "Fatigue"],
    causes: ["Cystic fibrosis", "Immune system problems", "Severe lung infections", "Aspiration", "Allergic bronchopulmonary aspergillosis"],
    prevention: ["Treat respiratory infections promptly", "Avoid lung irritants", "Get vaccinated", "Manage underlying conditions"],
    treatment: ["Airway clearance techniques", "Antibiotics", "Bronchodilators", "Anti-inflammatory drugs", "Surgery in severe cases"],
    riskFactors: ["Previous lung infections", "Immune deficiencies", "Cystic fibrosis", "COPD", "Rheumatoid arthritis"],
    whenToSeeDoctor: "See a doctor if you have a persistent cough with mucus production or if you're coughing up blood."
  },
  {
    id: "lung-cancer",
    name: "Lung Cancer",
    category: "Respiratory",
    description: "Cancer that begins in the lungs, most commonly in people who smoke, though it can occur in non-smokers as well.",
    symptoms: ["New persistent cough", "Coughing up blood", "Shortness of breath", "Chest pain", "Hoarseness", "Weight loss", "Bone pain", "Headache"],
    causes: ["Smoking", "Secondhand smoke", "Radon exposure", "Asbestos exposure", "Family history"],
    prevention: ["Don't smoke", "Avoid secondhand smoke", "Test home for radon", "Avoid carcinogens at work", "Eat fruits and vegetables"],
    treatment: ["Surgery", "Radiation therapy", "Chemotherapy", "Targeted drug therapy", "Immunotherapy"],
    riskFactors: ["Smoking", "Secondhand smoke exposure", "Radon exposure", "Family history", "Previous radiation therapy"],
    whenToSeeDoctor: "See a doctor if you have any persistent symptoms, especially if you smoke or have smoked."
  },

  // NEUROLOGICAL DISEASES
  {
    id: "parkinsons",
    name: "Parkinson's Disease",
    category: "Neurological",
    description: "A progressive nervous system disorder that affects movement, causing tremors, stiffness, and slowing of movement.",
    symptoms: ["Tremor", "Slowed movement", "Rigid muscles", "Impaired posture", "Loss of automatic movements", "Speech changes", "Writing changes"],
    causes: ["Loss of dopamine-producing neurons", "Genetic mutations", "Environmental triggers"],
    prevention: ["Regular aerobic exercise", "Caffeine may have protective effects", "Avoid toxins"],
    treatment: ["Carbidopa-levodopa", "Dopamine agonists", "MAO B inhibitors", "Deep brain stimulation", "Physical therapy"],
    riskFactors: ["Age", "Heredity", "Sex (men more common)", "Exposure to toxins"],
    whenToSeeDoctor: "See a doctor if you have any symptoms associated with Parkinson's disease, such as tremors or slow movements."
  },
  {
    id: "multiple-sclerosis",
    name: "Multiple Sclerosis",
    category: "Neurological",
    description: "A disease in which the immune system attacks the protective sheath (myelin) that covers nerve fibers, causing communication problems between brain and body.",
    symptoms: ["Numbness or weakness in limbs", "Electric-shock sensations", "Tremor", "Vision problems", "Slurred speech", "Fatigue", "Dizziness", "Bladder problems"],
    causes: ["Autoimmune response", "Genetics", "Environmental factors", "Infections may trigger"],
    prevention: ["No proven prevention", "Vitamin D may help", "Don't smoke", "Maintain healthy weight"],
    treatment: ["Corticosteroids", "Plasma exchange", "Disease-modifying therapies", "Physical therapy", "Muscle relaxants"],
    riskFactors: ["Age 20-40", "Female sex", "Family history", "Certain infections", "Vitamin D deficiency", "Autoimmune diseases", "Smoking"],
    whenToSeeDoctor: "See a doctor if you experience unexplained symptoms that concern you, especially numbness, vision problems, or weakness."
  },
  {
    id: "epilepsy",
    name: "Epilepsy",
    category: "Neurological",
    description: "A central nervous system disorder in which brain activity becomes abnormal, causing seizures and sometimes loss of awareness.",
    symptoms: ["Temporary confusion", "Staring spell", "Uncontrollable jerking movements", "Loss of consciousness", "Psychic symptoms", "Fear or anxiety"],
    causes: ["Genetic influence", "Head trauma", "Brain conditions", "Infectious diseases", "Prenatal injury", "Developmental disorders"],
    prevention: ["Wear seatbelts", "Wear helmets", "Reduce stroke and heart disease risk", "Good prenatal care", "Prevent infections"],
    treatment: ["Anti-seizure medications", "Ketogenic diet", "Vagus nerve stimulation", "Deep brain stimulation", "Surgery"],
    riskFactors: ["Age (most common in children and older adults)", "Family history", "Head injuries", "Stroke", "Dementia", "Brain infections"],
    whenToSeeDoctor: "Seek immediate help if a seizure lasts more than 5 minutes, breathing doesn't resume, a second seizure follows, or if it's the first seizure."
  },
  {
    id: "neuropathy",
    name: "Peripheral Neuropathy",
    category: "Neurological",
    description: "Damage to the peripheral nerves causing weakness, numbness, and pain, usually in hands and feet.",
    symptoms: ["Gradual numbness", "Sharp or burning pain", "Extreme sensitivity to touch", "Muscle weakness", "Lack of coordination", "Heat intolerance"],
    causes: ["Diabetes", "Alcoholism", "Autoimmune diseases", "Infections", "Inherited disorders", "Tumors", "Vitamin deficiencies"],
    prevention: ["Manage diabetes", "Avoid excessive alcohol", "Eat a healthy diet", "Exercise regularly", "Avoid toxins"],
    treatment: ["Treating underlying cause", "Pain medications", "Transcutaneous electrical nerve stimulation", "Physical therapy", "Surgery"],
    riskFactors: ["Diabetes", "Alcohol abuse", "Vitamin deficiencies", "Infections", "Autoimmune diseases", "Kidney or liver disease"],
    whenToSeeDoctor: "See a doctor if you notice unusual tingling, weakness, or pain in your hands or feet."
  },
  {
    id: "meningitis",
    name: "Meningitis",
    category: "Neurological",
    description: "Inflammation of the membranes surrounding the brain and spinal cord, usually due to infection.",
    symptoms: ["Sudden high fever", "Stiff neck", "Severe headache", "Nausea or vomiting", "Confusion", "Sensitivity to light", "Sleepiness", "Skin rash (in some cases)"],
    causes: ["Viral infections (most common)", "Bacterial infections", "Fungal infections", "Parasitic infections"],
    prevention: ["Vaccination", "Good hygiene", "Don't share items", "Boost immune system", "Avoid close contact with infected persons"],
    treatment: ["Antibiotics for bacterial", "Antiviral medications", "Corticosteroids", "Rest and fluids", "Hospitalization often required"],
    riskFactors: ["Skipping vaccinations", "Age (most common in children under 5)", "Living in community settings", "Pregnancy", "Compromised immune system"],
    whenToSeeDoctor: "Seek immediate medical care if you suspect meningitis - it can be life-threatening."
  },

  // MENTAL HEALTH
  {
    id: "bipolar-disorder",
    name: "Bipolar Disorder",
    category: "Mental Health",
    description: "A mental health condition that causes extreme mood swings including emotional highs (mania) and lows (depression).",
    symptoms: ["Episodes of mania or hypomania", "Depressive episodes", "Unusual talkativeness", "Racing thoughts", "Decreased need for sleep", "Poor decision-making", "Feeling hopeless"],
    causes: ["Genetics", "Brain structure and function", "Environmental factors"],
    prevention: ["Early treatment", "Avoid drugs and alcohol", "Manage stress", "Sleep regularly", "Know warning signs"],
    treatment: ["Mood stabilizers", "Antipsychotics", "Antidepressants", "Psychotherapy", "Lifestyle management"],
    riskFactors: ["Having a first-degree relative with bipolar", "Periods of high stress", "Drug or alcohol abuse"],
    whenToSeeDoctor: "See a doctor if you have extreme mood swings that affect your daily life, or if you have suicidal thoughts."
  },
  {
    id: "ocd",
    name: "Obsessive-Compulsive Disorder",
    category: "Mental Health",
    description: "A disorder featuring unreasonable thoughts and fears (obsessions) that lead to compulsive behaviors.",
    symptoms: ["Fear of contamination", "Needing things orderly", "Aggressive thoughts", "Unwanted thoughts", "Excessive cleaning", "Ordering and arranging", "Checking behaviors"],
    causes: ["Biology", "Genetics", "Learning from watching family", "Insufficient serotonin"],
    prevention: ["Early treatment", "Stress management", "Get enough sleep", "Avoid caffeine and alcohol"],
    treatment: ["Cognitive behavioral therapy", "Exposure and response prevention", "SSRIs", "Antipsychotic medications"],
    riskFactors: ["Family history", "Stressful life events", "Other mental health disorders"],
    whenToSeeDoctor: "See a doctor if obsessions and compulsions affect your quality of life."
  },
  {
    id: "ptsd",
    name: "Post-Traumatic Stress Disorder",
    category: "Mental Health",
    description: "A mental health condition triggered by experiencing or witnessing a terrifying event.",
    symptoms: ["Flashbacks", "Nightmares", "Severe anxiety", "Uncontrollable thoughts about event", "Avoidance", "Negative changes in thinking", "Changes in emotional reactions"],
    causes: ["Traumatic events", "Combat exposure", "Physical or sexual assault", "Accidents", "Natural disasters"],
    prevention: ["Support after trauma", "Early treatment", "Building resilience", "Strong support system"],
    treatment: ["Cognitive therapy", "Exposure therapy", "EMDR", "Antidepressants", "Anti-anxiety medications"],
    riskFactors: ["Experiencing trauma", "Having other mental health problems", "Lacking support", "Having blood relatives with mental health problems", "Jobs that increase trauma exposure"],
    whenToSeeDoctor: "See a doctor if you have disturbing thoughts about a traumatic event for more than a month."
  },
  {
    id: "eating-disorder-anorexia",
    name: "Anorexia Nervosa",
    category: "Mental Health",
    description: "An eating disorder characterized by abnormally low body weight, intense fear of gaining weight, and distorted perception of body weight.",
    symptoms: ["Extreme weight loss", "Thin appearance", "Abnormal blood counts", "Fatigue", "Insomnia", "Dizziness", "Hair loss", "Absence of menstruation"],
    causes: ["Biological factors", "Psychological factors", "Environmental factors"],
    prevention: ["Promote healthy body image", "Address warning signs early", "Build self-esteem", "Avoid dieting discussions"],
    treatment: ["Psychotherapy", "Nutritional counseling", "Medical monitoring", "Hospitalization if needed", "Medications for associated conditions"],
    riskFactors: ["Being female", "Being young", "Genetics", "Family history", "Dieting", "Transitions", "Media influence"],
    whenToSeeDoctor: "Seek help immediately if you or someone you know shows signs of an eating disorder."
  },
  {
    id: "adhd",
    name: "ADHD (Attention-Deficit/Hyperactivity Disorder)",
    category: "Mental Health",
    description: "A chronic condition including attention difficulty, hyperactivity, and impulsiveness.",
    symptoms: ["Difficulty paying attention", "Hyperactivity", "Impulsive behavior", "Trouble organizing", "Poor time management", "Difficulty following through", "Frequent mood swings"],
    causes: ["Genetics", "Brain anatomy", "Premature birth", "Toxin exposure", "Brain injuries"],
    prevention: ["Avoid toxins during pregnancy", "Avoid alcohol and drugs during pregnancy", "Limit screen time for children"],
    treatment: ["Stimulant medications", "Non-stimulant medications", "Behavioral therapy", "Education and training", "Lifestyle changes"],
    riskFactors: ["Family history", "Exposure to toxins", "Maternal drug or alcohol use", "Premature birth"],
    whenToSeeDoctor: "See a doctor if inattention, hyperactivity, or impulsive behavior consistently disrupts your life."
  },

  // AUTOIMMUNE DISEASES
  {
    id: "lupus",
    name: "Systemic Lupus Erythematosus",
    category: "Autoimmune",
    description: "A chronic autoimmune disease where the immune system attacks its own tissues, affecting skin, joints, kidneys, brain, and other organs.",
    symptoms: ["Butterfly-shaped facial rash", "Fatigue", "Fever", "Joint pain and swelling", "Skin lesions", "Fingers turning white or blue", "Shortness of breath", "Dry eyes"],
    causes: ["Genetics", "Hormones", "Environmental factors", "Certain medications"],
    prevention: ["Avoid sun exposure", "Don't smoke", "Exercise regularly", "Eat a healthy diet"],
    treatment: ["NSAIDs", "Antimalarial drugs", "Corticosteroids", "Immunosuppressants", "Biologics"],
    riskFactors: ["Being female", "Age 15-45", "African American, Hispanic, or Asian descent"],
    whenToSeeDoctor: "See a doctor if you develop unexplained rash, ongoing fever, persistent fatigue, or joint pain."
  },
  {
    id: "psoriasis",
    name: "Psoriasis",
    category: "Autoimmune",
    description: "A skin disease that causes red, itchy scaly patches, most commonly on the knees, elbows, trunk, and scalp.",
    symptoms: ["Red patches of skin covered with silvery scales", "Dry cracked skin", "Itching or burning", "Thickened nails", "Stiff and swollen joints"],
    causes: ["Immune system dysfunction", "Genetics", "Environmental triggers"],
    prevention: ["Moisturize", "Avoid triggers", "Manage stress", "Don't smoke", "Limit alcohol"],
    treatment: ["Topical treatments", "Light therapy", "Oral or injected medications", "Biologics"],
    riskFactors: ["Family history", "Stress", "Obesity", "Smoking"],
    whenToSeeDoctor: "See a doctor if psoriasis becomes widespread, causes discomfort, or affects your quality of life."
  },
  {
    id: "crohns-disease",
    name: "Crohn's Disease",
    category: "Autoimmune",
    description: "An inflammatory bowel disease that causes inflammation of the digestive tract, leading to abdominal pain, severe diarrhea, and malnutrition.",
    symptoms: ["Diarrhea", "Fever", "Fatigue", "Abdominal pain", "Blood in stool", "Mouth sores", "Reduced appetite", "Weight loss"],
    causes: ["Immune system dysfunction", "Heredity", "Environmental factors"],
    prevention: ["No known prevention", "Eating smaller meals", "Staying hydrated", "Keeping a food diary"],
    treatment: ["Anti-inflammatory drugs", "Immune system suppressors", "Antibiotics", "Nutrition therapy", "Surgery"],
    riskFactors: ["Age under 30", "Family history", "Cigarette smoking", "NSAIDs", "Living in urban area"],
    whenToSeeDoctor: "See a doctor if you have persistent changes in bowel habits or blood in your stool."
  },
  {
    id: "ulcerative-colitis",
    name: "Ulcerative Colitis",
    category: "Autoimmune",
    description: "An inflammatory bowel disease that causes inflammation and ulcers in the digestive tract, affecting the innermost lining of the large intestine and rectum.",
    symptoms: ["Diarrhea with blood or pus", "Abdominal pain", "Rectal pain", "Rectal bleeding", "Urgency to defecate", "Weight loss", "Fatigue", "Fever"],
    causes: ["Immune system malfunction", "Heredity", "Environmental factors"],
    prevention: ["No known prevention", "Regular check-ups", "Managing stress"],
    treatment: ["Aminosalicylates", "Corticosteroids", "Immunomodulators", "Biologics", "Surgery"],
    riskFactors: ["Age under 30", "White or Ashkenazi Jewish heritage", "Family history"],
    whenToSeeDoctor: "See a doctor if you experience persistent changes in bowel habits or signs of ulcerative colitis."
  },
  {
    id: "celiac-disease",
    name: "Celiac Disease",
    category: "Autoimmune",
    description: "An immune reaction to eating gluten that damages the small intestine's lining and prevents absorption of nutrients.",
    symptoms: ["Diarrhea", "Bloating and gas", "Fatigue", "Weight loss", "Anemia", "Osteoporosis", "Skin rash", "Mouth ulcers"],
    causes: ["Eating gluten triggers immune response", "Genetics", "Environmental factors"],
    prevention: ["No prevention, but following gluten-free diet prevents symptoms"],
    treatment: ["Strict gluten-free diet", "Vitamin and mineral supplements", "Medications to control intestinal inflammation"],
    riskFactors: ["Family history", "Type 1 diabetes", "Down syndrome", "Autoimmune thyroid disease", "Microscopic colitis"],
    whenToSeeDoctor: "See a doctor if you have diarrhea or digestive discomfort for more than two weeks."
  },
  {
    id: "graves-disease",
    name: "Graves' Disease",
    category: "Autoimmune",
    description: "An immune system disorder that results in the overproduction of thyroid hormones (hyperthyroidism).",
    symptoms: ["Anxiety and irritability", "Tremor", "Heat sensitivity", "Weight loss", "Enlarged thyroid", "Change in menstrual cycles", "Bulging eyes", "Thick, red skin on shins"],
    causes: ["Immune system malfunction produces antibodies that stimulate thyroid"],
    prevention: ["No known prevention", "Manage stress", "Quit smoking"],
    treatment: ["Radioiodine therapy", "Anti-thyroid medications", "Beta blockers", "Surgery"],
    riskFactors: ["Family history", "Being female", "Age under 40", "Other autoimmune disorders", "Pregnancy", "Smoking", "Emotional or physical stress"],
    whenToSeeDoctor: "See a doctor if you have signs of hyperthyroidism or notice eye changes."
  },
  {
    id: "hashimotos",
    name: "Hashimoto's Thyroiditis",
    category: "Autoimmune",
    description: "A condition where the immune system attacks the thyroid, leading to underactive thyroid (hypothyroidism).",
    symptoms: ["Fatigue", "Increased cold sensitivity", "Constipation", "Pale, dry skin", "Puffy face", "Muscle weakness", "Unexplained weight gain", "Depression"],
    causes: ["Immune system attacks thyroid", "Genetics", "Environmental factors"],
    prevention: ["No known prevention"],
    treatment: ["Thyroid hormone replacement medication", "Regular monitoring"],
    riskFactors: ["Being female", "Middle age", "Other autoimmune disease", "Family history", "Excessive iodine", "Radiation exposure"],
    whenToSeeDoctor: "See a doctor if you have symptoms of hypothyroidism such as fatigue, constipation, or unexplained weight gain."
  },

  // METABOLIC DISEASES
  {
    id: "type-1-diabetes",
    name: "Type 1 Diabetes",
    category: "Metabolic",
    description: "A chronic condition in which the pancreas produces little or no insulin, requiring daily insulin administration.",
    symptoms: ["Increased thirst", "Frequent urination", "Bed-wetting in children", "Extreme hunger", "Unintended weight loss", "Irritability", "Fatigue", "Blurred vision"],
    causes: ["Immune system destroys insulin-producing cells", "Genetics", "Environmental factors"],
    prevention: ["No known prevention"],
    treatment: ["Insulin therapy", "Blood sugar monitoring", "Carbohydrate counting", "Healthy eating", "Regular exercise"],
    riskFactors: ["Family history", "Genetics", "Geography (more common farther from equator)", "Age (peaks at 4-7 and 10-14 years)"],
    whenToSeeDoctor: "See a doctor if you notice signs of diabetes in yourself or your child."
  },
  {
    id: "metabolic-syndrome",
    name: "Metabolic Syndrome",
    category: "Metabolic",
    description: "A cluster of conditions including high blood pressure, high blood sugar, excess body fat around the waist, and abnormal cholesterol levels.",
    symptoms: ["Large waist circumference", "High triglycerides", "Low HDL cholesterol", "High blood pressure", "High fasting blood sugar"],
    causes: ["Obesity", "Insulin resistance", "Inactivity", "Genetic factors"],
    prevention: ["Exercise regularly", "Lose weight", "Eat healthy", "Manage stress", "Quit smoking"],
    treatment: ["Lifestyle changes", "Weight loss medications", "Cholesterol medications", "Blood pressure medications", "Diabetes medications"],
    riskFactors: ["Age", "Obesity", "Diabetes", "Other diseases", "Race/ethnicity"],
    whenToSeeDoctor: "See a doctor if you have a large waist or symptoms of high blood sugar or high blood pressure."
  },
  {
    id: "gout",
    name: "Gout",
    category: "Metabolic",
    description: "A complex form of arthritis characterized by sudden, severe attacks of pain, swelling, and redness in joints.",
    symptoms: ["Intense joint pain", "Lingering discomfort", "Inflammation and redness", "Limited range of motion"],
    causes: ["Urate crystal accumulation", "High uric acid levels", "Diet high in purines", "Obesity", "Medical conditions"],
    prevention: ["Stay hydrated", "Limit alcohol", "Get protein from low-fat dairy", "Limit high-purine foods", "Maintain healthy weight"],
    treatment: ["NSAIDs", "Colchicine", "Corticosteroids", "Medications to block uric acid production", "Medications to improve uric acid removal"],
    riskFactors: ["High-purine diet", "Obesity", "Medical conditions", "Certain medications", "Family history", "Age and sex", "Recent surgery or trauma"],
    whenToSeeDoctor: "See a doctor if you experience sudden, intense joint pain, especially in the big toe."
  },
  {
    id: "hyperthyroidism",
    name: "Hyperthyroidism",
    category: "Metabolic",
    description: "A condition where the thyroid gland produces too much thyroxine hormone, accelerating the body's metabolism.",
    symptoms: ["Unintentional weight loss", "Rapid heartbeat", "Irregular heartbeat", "Increased appetite", "Nervousness", "Tremor", "Sweating", "Changes in menstrual patterns"],
    causes: ["Graves' disease", "Thyroid nodules", "Thyroiditis", "Excessive iodine", "Too much thyroid medication"],
    prevention: ["No specific prevention", "Regular thyroid function tests if at risk"],
    treatment: ["Radioiodine therapy", "Anti-thyroid medications", "Beta blockers", "Surgery"],
    riskFactors: ["Family history", "Female sex", "Previous thyroid problems", "Pernicious anemia", "Type 1 diabetes"],
    whenToSeeDoctor: "See a doctor if you have unexplained weight loss, rapid heartbeat, or other signs of hyperthyroidism."
  },
  {
    id: "hypothyroidism",
    name: "Hypothyroidism",
    category: "Metabolic",
    description: "A condition where the thyroid gland doesn't produce enough thyroid hormone, slowing metabolism.",
    symptoms: ["Fatigue", "Increased cold sensitivity", "Constipation", "Dry skin", "Weight gain", "Puffy face", "Hoarseness", "Muscle weakness"],
    causes: ["Autoimmune disease", "Thyroid surgery", "Radiation therapy", "Certain medications", "Iodine deficiency"],
    prevention: ["Regular thyroid function tests if at risk", "Adequate iodine intake"],
    treatment: ["Synthetic thyroid hormone", "Regular monitoring", "Dosage adjustments"],
    riskFactors: ["Being female", "Age over 60", "Family history", "Autoimmune diseases", "Treatment with radioactive iodine or anti-thyroid medications"],
    whenToSeeDoctor: "See a doctor if you have unexplained fatigue, constipation, dry skin, or unexplained weight gain."
  },

  // GASTROINTESTINAL DISEASES
  {
    id: "gastritis",
    name: "Gastritis",
    category: "Gastrointestinal",
    description: "Inflammation of the stomach lining that can cause pain, nausea, and vomiting.",
    symptoms: ["Gnawing pain in upper abdomen", "Nausea", "Vomiting", "Feeling of fullness", "Bloating", "Burning feeling in stomach"],
    causes: ["H. pylori infection", "Regular use of pain relievers", "Excessive alcohol", "Stress", "Autoimmune response", "Bile reflux"],
    prevention: ["Avoid irritating foods", "Limit alcohol", "Manage stress", "Avoid NSAIDs when possible"],
    treatment: ["Antacids", "H2 blockers", "Proton pump inhibitors", "Antibiotics for H. pylori", "Avoiding irritants"],
    riskFactors: ["H. pylori infection", "Regular NSAID use", "Older age", "Excessive alcohol", "Stress", "Autoimmune disorders"],
    whenToSeeDoctor: "See a doctor if you have stomach pain lasting more than a week, or if you vomit blood."
  },
  {
    id: "peptic-ulcer",
    name: "Peptic Ulcer Disease",
    category: "Gastrointestinal",
    description: "Open sores that develop on the inside lining of the stomach and the upper portion of the small intestine.",
    symptoms: ["Burning stomach pain", "Feeling of fullness", "Bloating", "Intolerance to fatty foods", "Heartburn", "Nausea"],
    causes: ["H. pylori bacteria", "Regular use of aspirin and NSAIDs", "Other medications"],
    prevention: ["Protect yourself from infections", "Use caution with pain relievers", "Limit alcohol", "Don't smoke", "Manage stress"],
    treatment: ["Antibiotics", "Proton pump inhibitors", "H2 blockers", "Antacids", "Cytoprotective agents"],
    riskFactors: ["H. pylori infection", "Regular NSAID use", "Smoking", "Drinking alcohol", "Untreated stress", "Spicy foods (aggravate, not cause)"],
    whenToSeeDoctor: "See a doctor if you have severe stomach pain, vomiting blood, or blood in stool."
  },
  {
    id: "ibs",
    name: "Irritable Bowel Syndrome",
    category: "Gastrointestinal",
    description: "A common disorder affecting the large intestine causing cramping, abdominal pain, bloating, gas, diarrhea, and constipation.",
    symptoms: ["Cramping", "Abdominal pain", "Bloating", "Gas", "Diarrhea or constipation", "Mucus in stool"],
    causes: ["Muscle contractions in intestine", "Nervous system abnormalities", "Severe infection", "Changes in gut microbes"],
    prevention: ["Manage stress", "Eat at regular times", "Exercise regularly", "Get enough sleep"],
    treatment: ["Dietary changes", "Fiber supplements", "Anti-diarrheal medications", "Anticholinergic medications", "SSRIs", "Probiotics"],
    riskFactors: ["Being young", "Being female", "Family history", "Mental health problems"],
    whenToSeeDoctor: "See a doctor if you have persistent changes in bowel habits or other signs of a more serious condition."
  },
  {
    id: "gerd",
    name: "GERD (Gastroesophageal Reflux Disease)",
    category: "Gastrointestinal",
    description: "A chronic digestive disease where stomach acid flows back into the esophagus, irritating its lining.",
    symptoms: ["Heartburn", "Chest pain", "Difficulty swallowing", "Regurgitation", "Sensation of lump in throat", "Chronic cough", "Laryngitis", "Disrupted sleep"],
    causes: ["Frequent acid reflux", "Weak lower esophageal sphincter", "Hiatal hernia", "Obesity", "Pregnancy"],
    prevention: ["Maintain healthy weight", "Avoid tight clothing", "Avoid trigger foods", "Don't lie down after meals", "Elevate head of bed", "Don't smoke"],
    treatment: ["Antacids", "H2 blockers", "Proton pump inhibitors", "Medications to strengthen lower esophageal sphincter", "Surgery in severe cases"],
    riskFactors: ["Obesity", "Hiatal hernia", "Pregnancy", "Connective tissue disorders", "Delayed stomach emptying"],
    whenToSeeDoctor: "See a doctor if you have frequent heartburn, difficulty swallowing, or chest pain."
  },
  {
    id: "diverticulitis",
    name: "Diverticulitis",
    category: "Gastrointestinal",
    description: "Inflammation or infection of small pouches (diverticula) that develop in the walls of the intestines.",
    symptoms: ["Abdominal pain (usually left side)", "Fever", "Nausea and vomiting", "Abdominal tenderness", "Constipation or diarrhea"],
    causes: ["Formation of diverticula", "Bacterial infection", "Low-fiber diet", "Aging", "Lack of exercise"],
    prevention: ["Eat more fiber", "Drink plenty of fluids", "Exercise regularly", "Avoid smoking"],
    treatment: ["Antibiotics", "Liquid diet", "Rest", "Pain medications", "Surgery for complications"],
    riskFactors: ["Aging", "Obesity", "Smoking", "Lack of exercise", "Low-fiber diet", "Certain medications"],
    whenToSeeDoctor: "See a doctor if you have persistent abdominal pain with fever."
  },
  {
    id: "pancreatitis",
    name: "Pancreatitis",
    category: "Gastrointestinal",
    description: "Inflammation of the pancreas that can occur as acute attacks or chronic condition.",
    symptoms: ["Upper abdominal pain", "Pain radiating to back", "Pain worsening after eating", "Fever", "Rapid pulse", "Nausea", "Vomiting", "Tender abdomen"],
    causes: ["Gallstones", "Alcoholism", "Certain medications", "High triglycerides", "Abdominal surgery", "Infections"],
    prevention: ["Don't drink alcohol excessively", "Don't smoke", "Maintain healthy weight", "Eat low-fat diet"],
    treatment: ["Fasting", "Pain medications", "IV fluids", "Enzyme supplements", "Treatment of underlying cause", "Surgery"],
    riskFactors: ["Heavy alcohol use", "Gallstones", "Obesity", "Diabetes", "Family history", "Smoking"],
    whenToSeeDoctor: "Seek immediate care if you have severe abdominal pain that doesn't improve."
  },
  {
    id: "gallstones",
    name: "Gallstones",
    category: "Gastrointestinal",
    description: "Hardened deposits of digestive fluid that can form in the gallbladder.",
    symptoms: ["Sudden intense pain in upper right abdomen", "Pain in center of abdomen", "Back pain between shoulder blades", "Right shoulder pain", "Nausea or vomiting"],
    causes: ["Too much cholesterol in bile", "Too much bilirubin", "Gallbladder doesn't empty correctly"],
    prevention: ["Don't skip meals", "Lose weight slowly", "Maintain healthy weight", "Eat high-fiber foods", "Exercise"],
    treatment: ["Observation if no symptoms", "Cholecystectomy (gallbladder removal)", "Medications to dissolve stones"],
    riskFactors: ["Being female", "Age 40+", "Obesity", "High-fat diet", "Rapid weight loss", "Diabetes", "Family history"],
    whenToSeeDoctor: "See a doctor if you have intense abdominal pain, yellowing of skin/eyes, or high fever with chills."
  },
  {
    id: "liver-cirrhosis",
    name: "Liver Cirrhosis",
    category: "Gastrointestinal",
    description: "Late-stage scarring of the liver caused by many forms of liver diseases and conditions.",
    symptoms: ["Fatigue", "Easily bruising", "Itchy skin", "Yellow discoloration of skin and eyes", "Fluid accumulation in abdomen", "Loss of appetite", "Spider-like blood vessels", "Redness in palms"],
    causes: ["Chronic alcohol abuse", "Chronic viral hepatitis", "Fat accumulating in liver", "Iron buildup", "Cystic fibrosis"],
    prevention: ["Don't drink alcohol excessively", "Maintain healthy weight", "Reduce risk of hepatitis", "Avoid risky behaviors"],
    treatment: ["Treating underlying cause", "Medications for complications", "Weight loss for fatty liver", "Liver transplant for end-stage"],
    riskFactors: ["Drinking too much alcohol", "Being overweight", "Having viral hepatitis"],
    whenToSeeDoctor: "See a doctor if you have symptoms of cirrhosis, especially jaundice or abdominal swelling."
  },

  // INFECTIOUS DISEASES
  {
    id: "malaria",
    name: "Malaria",
    category: "Infectious",
    description: "A life-threatening disease caused by parasites transmitted through the bites of infected mosquitoes.",
    symptoms: ["Fever", "Chills", "Sweating", "Headache", "Nausea and vomiting", "Muscle pain", "Fatigue", "Chest or abdominal pain"],
    causes: ["Plasmodium parasites", "Transmitted by Anopheles mosquitoes", "Blood transfusion", "Shared needles", "Mother to unborn child"],
    prevention: ["Antimalarial medications", "Use insect repellent", "Sleep under mosquito nets", "Wear protective clothing", "Spray insecticides"],
    treatment: ["Antimalarial drugs", "Hospitalization for severe cases", "Supportive care"],
    riskFactors: ["Living in or visiting malaria-endemic areas", "Young children", "Pregnant women", "Travelers from non-endemic areas"],
    whenToSeeDoctor: "See a doctor immediately if you develop fever after visiting a malaria-risk area."
  },
  {
    id: "dengue",
    name: "Dengue Fever",
    category: "Infectious",
    description: "A mosquito-borne viral disease that causes high fever, severe headache, and joint and muscle pain.",
    symptoms: ["High fever", "Severe headache", "Pain behind eyes", "Joint and muscle pain", "Fatigue", "Nausea", "Vomiting", "Skin rash", "Mild bleeding"],
    causes: ["Dengue virus", "Transmitted by Aedes mosquitoes"],
    prevention: ["Avoid mosquito bites", "Use insect repellent", "Wear protective clothing", "Remove standing water", "Dengue vaccine in some areas"],
    treatment: ["Rest", "Fluids", "Acetaminophen for pain", "Avoid aspirin and NSAIDs", "Hospitalization for severe dengue"],
    riskFactors: ["Living in tropical and subtropical areas", "Previous dengue infection", "Young children and elderly"],
    whenToSeeDoctor: "Seek immediate care if you have severe abdominal pain, persistent vomiting, or bleeding."
  },
  {
    id: "typhoid",
    name: "Typhoid Fever",
    category: "Infectious",
    description: "A bacterial infection that can spread throughout the body, affecting many organs.",
    symptoms: ["Sustained high fever", "Weakness", "Stomach pain", "Headache", "Loss of appetite", "Rash", "Constipation or diarrhea"],
    causes: ["Salmonella typhi bacteria", "Contaminated food or water", "Close contact with infected person"],
    prevention: ["Vaccination", "Drink safe water", "Avoid raw foods", "Wash hands frequently", "Avoid close contact with infected persons"],
    treatment: ["Antibiotics", "Fluids and electrolytes", "Rest", "Hospitalization for severe cases"],
    riskFactors: ["Traveling to endemic areas", "Working with Salmonella typhi", "Close contact with infected person"],
    whenToSeeDoctor: "See a doctor if you have a high fever and have recently traveled to an area where typhoid is common."
  },
  {
    id: "cholera",
    name: "Cholera",
    category: "Infectious",
    description: "An acute diarrheal illness caused by infection of the intestine with Vibrio cholerae bacteria.",
    symptoms: ["Profuse watery diarrhea", "Vomiting", "Leg cramps", "Rapid heart rate", "Low blood pressure", "Thirst", "Rapid dehydration"],
    causes: ["Vibrio cholerae bacteria", "Contaminated water", "Raw or undercooked seafood", "Contaminated foods"],
    prevention: ["Drink safe water", "Wash hands", "Eat thoroughly cooked food", "Cholera vaccine", "Avoid raw foods in endemic areas"],
    treatment: ["Oral rehydration salts", "Intravenous fluids for severe cases", "Antibiotics", "Zinc supplements"],
    riskFactors: ["Poor sanitation", "Reduced or nonexistent stomach acid", "Household exposure", "Type O blood", "Raw shellfish"],
    whenToSeeDoctor: "Seek immediate medical attention for severe watery diarrhea with dehydration."
  },
  {
    id: "hiv-aids",
    name: "HIV/AIDS",
    category: "Infectious",
    description: "A chronic, potentially life-threatening condition caused by the human immunodeficiency virus that damages the immune system.",
    symptoms: ["Fever", "Headache", "Muscle aches", "Rash", "Sore throat", "Swollen lymph nodes", "Night sweats", "Chronic diarrhea", "Opportunistic infections"],
    causes: ["Human immunodeficiency virus", "Sexual contact", "Shared needles", "Blood transfusion", "Mother to child transmission"],
    prevention: ["Use condoms", "Don't share needles", "Get tested", "PrEP for high-risk individuals", "Treatment as prevention"],
    treatment: ["Antiretroviral therapy (ART)", "Treatment of opportunistic infections", "Supportive care"],
    riskFactors: ["Unprotected sex", "Multiple sex partners", "STIs", "Sharing needles", "Accidental needle sticks"],
    whenToSeeDoctor: "Get tested if you have risk factors or flu-like symptoms after possible exposure."
  },
  {
    id: "influenza",
    name: "Influenza (Flu)",
    category: "Infectious",
    description: "A viral infection that attacks the respiratory system — nose, throat, and lungs.",
    symptoms: ["Fever", "Chills", "Muscle aches", "Cough", "Congestion", "Runny nose", "Headaches", "Fatigue"],
    causes: ["Influenza viruses (A, B, C)", "Airborne transmission", "Contact with contaminated surfaces"],
    prevention: ["Annual flu vaccination", "Wash hands frequently", "Avoid crowds during flu season", "Cover coughs and sneezes", "Stay home when sick"],
    treatment: ["Rest", "Fluids", "Antiviral medications if caught early", "Over-the-counter symptom relief"],
    riskFactors: ["Age under 5 or over 65", "Chronic conditions", "Weakened immune system", "Obesity", "Pregnancy"],
    whenToSeeDoctor: "Seek emergency care for difficulty breathing, chest pain, confusion, or severe vomiting."
  },

  // ENDOCRINE DISEASES
  {
    id: "cushings-syndrome",
    name: "Cushing's Syndrome",
    category: "Endocrine",
    description: "A condition caused by prolonged exposure to high levels of the hormone cortisol.",
    symptoms: ["Weight gain especially in midsection", "Round face", "Pink or purple stretch marks", "Thin skin that bruises easily", "Slow healing", "Acne", "Fatigue", "Muscle weakness"],
    causes: ["Long-term use of corticosteroid medications", "Pituitary gland tumor", "Adrenal gland tumor", "Ectopic ACTH-secreting tumor"],
    prevention: ["Use lowest effective dose of corticosteroids", "Regular monitoring if on steroids"],
    treatment: ["Reducing corticosteroid use", "Surgery to remove tumors", "Radiation therapy", "Medications to control cortisol"],
    riskFactors: ["Taking high-dose corticosteroids", "Type 2 diabetes", "High blood pressure", "Obesity"],
    whenToSeeDoctor: "See a doctor if you're taking corticosteroids and developing symptoms, or have unexplained weight gain and weakness."
  },
  {
    id: "addisons-disease",
    name: "Addison's Disease",
    category: "Endocrine",
    description: "A disorder where the adrenal glands don't produce enough hormones.",
    symptoms: ["Extreme fatigue", "Weight loss", "Decreased appetite", "Darkening of skin", "Low blood pressure", "Salt craving", "Low blood sugar", "Nausea", "Muscle or joint pain"],
    causes: ["Autoimmune destruction of adrenal glands", "Tuberculosis", "Other infections", "Cancer spread to adrenal glands"],
    prevention: ["No known prevention", "Early treatment prevents crisis"],
    treatment: ["Hormone replacement therapy", "Managing salt in diet", "Increased medication during stress/illness"],
    riskFactors: ["Other autoimmune diseases", "Tuberculosis", "Certain fungal infections", "AIDS"],
    whenToSeeDoctor: "Seek emergency care if you have severe weakness, confusion, or pain in lower back or legs."
  },
  {
    id: "pcos",
    name: "Polycystic Ovary Syndrome (PCOS)",
    category: "Endocrine",
    description: "A hormonal disorder common among women of reproductive age, affecting the ovaries.",
    symptoms: ["Irregular periods", "Excess androgen (male hormone)", "Polycystic ovaries", "Weight gain", "Acne", "Male-pattern baldness", "Darkening of skin", "Infertility"],
    causes: ["Excess insulin", "Low-grade inflammation", "Heredity", "Excess androgen"],
    prevention: ["Maintain healthy weight", "Exercise regularly", "Eat healthy", "Limit carbohydrates"],
    treatment: ["Birth control pills", "Metformin", "Clomiphene for fertility", "Anti-androgen medications", "Lifestyle changes"],
    riskFactors: ["Family history", "Insulin resistance", "Obesity"],
    whenToSeeDoctor: "See a doctor if you have concerns about your menstrual periods or signs of excess androgen."
  },
  {
    id: "diabetes-insipidus",
    name: "Diabetes Insipidus",
    category: "Endocrine",
    description: "A rare disorder that causes an imbalance of fluids in the body, leading to intense thirst and excretion of large amounts of urine.",
    symptoms: ["Extreme thirst", "Producing large amounts of dilute urine", "Frequently needing to get up to urinate at night", "Dehydration", "Weakness", "Confusion"],
    causes: ["Problems with vasopressin (central)", "Kidneys not responding to vasopressin (nephrogenic)", "Damage during pregnancy", "Excessive water intake"],
    prevention: ["No known prevention for most causes"],
    treatment: ["Desmopressin for central DI", "Thiazide diuretics for nephrogenic DI", "Low-salt diet", "Adequate water intake"],
    riskFactors: ["Brain surgery", "Brain injury", "Genetic factors", "Kidney disease", "Certain medications"],
    whenToSeeDoctor: "See a doctor if you have excessive urination and extreme thirst."
  },

  // MUSCULOSKELETAL DISEASES
  {
    id: "fibromyalgia",
    name: "Fibromyalgia",
    category: "Musculoskeletal",
    description: "A disorder characterized by widespread musculoskeletal pain accompanied by fatigue, sleep, memory, and mood issues.",
    symptoms: ["Widespread pain", "Fatigue", "Cognitive difficulties (fibro fog)", "Sleep problems", "Headaches", "Depression", "Anxiety", "TMJ disorders"],
    causes: ["Genetics", "Infections", "Physical or emotional trauma", "Stress"],
    prevention: ["Manage stress", "Get enough sleep", "Exercise regularly", "Maintain healthy lifestyle"],
    treatment: ["Pain relievers", "Antidepressants", "Anti-seizure drugs", "Physical therapy", "Occupational therapy", "Counseling"],
    riskFactors: ["Sex (more common in women)", "Family history", "Other disorders like osteoarthritis, lupus, or rheumatoid arthritis"],
    whenToSeeDoctor: "See a doctor if you have widespread pain and fatigue that interferes with daily activities."
  },
  {
    id: "osteoporosis",
    name: "Osteoporosis",
    category: "Musculoskeletal",
    description: "A condition that weakens bones, making them fragile and more likely to break.",
    symptoms: ["Back pain from fractured vertebra", "Loss of height", "Stooped posture", "Bones that break easily"],
    causes: ["Aging", "Low calcium intake", "Eating disorders", "GI surgery", "Certain medications", "Medical conditions"],
    prevention: ["Adequate calcium and vitamin D", "Regular exercise", "Avoid smoking", "Limit alcohol", "Fall prevention"],
    treatment: ["Bisphosphonates", "Hormone therapy", "Bone-building medications", "Calcium and vitamin D supplements"],
    riskFactors: ["Female sex", "Older age", "Family history", "Small body frame", "Hormone levels", "Dietary factors", "Steroids"],
    whenToSeeDoctor: "See a doctor if you've had early menopause, taken steroids for months, or have a parent who had a hip fracture."
  },
  {
    id: "tendinitis",
    name: "Tendinitis",
    category: "Musculoskeletal",
    description: "Inflammation or irritation of a tendon, the thick fibrous cords that attach muscle to bone.",
    symptoms: ["Pain at tendon site", "Swelling", "Tenderness", "Pain worsening with movement", "Stiffness"],
    causes: ["Repetitive motion", "Sudden injury", "Age-related changes", "Poor posture", "Overuse"],
    prevention: ["Ease up on activities that cause pain", "Mix up exercises", "Improve technique", "Stretch regularly"],
    treatment: ["Rest", "Ice", "Compression", "Elevation", "Pain relievers", "Corticosteroid injections", "Physical therapy"],
    riskFactors: ["Age over 40", "Jobs with repetitive motions", "Sports activities", "Certain medical conditions"],
    whenToSeeDoctor: "See a doctor if self-care doesn't work within a few days or if pain is severe and sudden."
  },
  {
    id: "bursitis",
    name: "Bursitis",
    category: "Musculoskeletal",
    description: "Inflammation of the small, fluid-filled sacs (bursae) that cushion bones, tendons, and muscles near joints.",
    symptoms: ["Joint pain", "Stiffness", "Swelling", "Redness", "Pain with movement or pressure"],
    causes: ["Repetitive motions", "Prolonged pressure", "Injury", "Arthritis", "Gout", "Infection"],
    prevention: ["Kneel on pads", "Lift properly", "Take breaks", "Exercise", "Maintain healthy weight"],
    treatment: ["Rest", "Ice", "Pain medications", "Corticosteroid injections", "Physical therapy", "Antibiotics if infected"],
    riskFactors: ["Age", "Occupations with repetitive tasks", "Hobbies requiring repetitive motion", "Other conditions"],
    whenToSeeDoctor: "See a doctor if you have disabling joint pain, sudden inability to move a joint, or fever with swelling."
  },
  {
    id: "scoliosis",
    name: "Scoliosis",
    category: "Musculoskeletal",
    description: "A sideways curvature of the spine that most often is diagnosed in adolescents.",
    symptoms: ["Uneven shoulders", "One shoulder blade more prominent", "Uneven waist", "One hip higher than other", "Back pain"],
    causes: ["Unknown in most cases (idiopathic)", "Cerebral palsy", "Muscular dystrophy", "Birth defects", "Spinal injuries"],
    prevention: ["No known prevention for idiopathic scoliosis", "Early detection important"],
    treatment: ["Observation for mild cases", "Bracing for growing children", "Surgery for severe curves"],
    riskFactors: ["Age (typically appears during growth spurt)", "Sex (girls have higher risk of worsening)", "Family history"],
    whenToSeeDoctor: "See a doctor if you notice signs of scoliosis in your child or yourself."
  },
  {
    id: "herniated-disc",
    name: "Herniated Disc",
    category: "Musculoskeletal",
    description: "A problem with one of the rubbery cushions (discs) that sit between the vertebrae of the spine.",
    symptoms: ["Arm or leg pain", "Numbness or tingling", "Weakness in muscles", "Pain worsening with certain movements"],
    causes: ["Gradual wear and tear (disc degeneration)", "Lifting heavy objects", "Twisting", "Trauma"],
    prevention: ["Exercise regularly", "Maintain good posture", "Maintain healthy weight", "Don't smoke"],
    treatment: ["Pain medications", "Physical therapy", "Cortisone injections", "Surgery if conservative treatment fails"],
    riskFactors: ["Weight", "Occupation with repetitive lifting", "Genetics", "Smoking"],
    whenToSeeDoctor: "See a doctor if you have neck or back pain traveling to arm or leg, or numbness, tingling, or weakness."
  },

  // BLOOD DISORDERS
  {
    id: "anemia",
    name: "Anemia",
    category: "Blood Disorders",
    description: "A condition in which you lack enough healthy red blood cells to carry adequate oxygen to your body's tissues.",
    symptoms: ["Fatigue", "Weakness", "Pale or yellowish skin", "Irregular heartbeats", "Shortness of breath", "Dizziness", "Chest pain", "Cold hands and feet"],
    causes: ["Iron deficiency", "Vitamin deficiency", "Chronic diseases", "Bone marrow disease", "Hemolysis", "Sickle cell disease"],
    prevention: ["Eat iron-rich foods", "Eat vitamin C rich foods", "Eat foods with B-12 and folate", "Consider supplements if at risk"],
    treatment: ["Iron supplements", "Vitamin B-12 injections", "Blood transfusions", "Treating underlying conditions"],
    riskFactors: ["Poor diet", "Intestinal disorders", "Menstruation", "Pregnancy", "Chronic conditions", "Family history", "Age"],
    whenToSeeDoctor: "See a doctor if you feel fatigued for no reason, especially if you have risk factors for anemia."
  },
  {
    id: "hemophilia",
    name: "Hemophilia",
    category: "Blood Disorders",
    description: "A rare inherited bleeding disorder in which blood doesn't clot normally.",
    symptoms: ["Excessive bleeding from cuts", "Deep bruises", "Unexplained bleeding", "Blood in urine or stool", "Nosebleeds", "Tight joints from internal bleeding"],
    causes: ["Inherited gene mutations affecting clotting factors", "Acquired (rare)"],
    prevention: ["No prevention for inherited form", "Genetic counseling for family planning"],
    treatment: ["Clotting factor replacement", "Desmopressin", "Clot-preserving medications", "Physical therapy"],
    riskFactors: ["Family history", "Male sex (for most types)"],
    whenToSeeDoctor: "Seek emergency care for head injuries or signs of bleeding in brain (prolonged headache, vomiting, drowsiness)."
  },
  {
    id: "leukemia",
    name: "Leukemia",
    category: "Blood Disorders",
    description: "Cancer of the body's blood-forming tissues, including the bone marrow and lymphatic system.",
    symptoms: ["Fever or chills", "Persistent fatigue", "Frequent infections", "Weight loss", "Swollen lymph nodes", "Easy bleeding or bruising", "Recurrent nosebleeds", "Tiny red spots on skin"],
    causes: ["Genetic abnormalities", "Previous cancer treatment", "Genetic disorders", "Exposure to certain chemicals"],
    prevention: ["No known prevention", "Avoid exposure to high doses of radiation and benzene"],
    treatment: ["Chemotherapy", "Targeted therapy", "Radiation therapy", "Bone marrow transplant", "Immunotherapy"],
    riskFactors: ["Previous cancer treatment", "Genetic disorders", "Exposure to certain chemicals", "Smoking", "Family history"],
    whenToSeeDoctor: "See a doctor if you have persistent symptoms that worry you."
  },
  {
    id: "lymphoma",
    name: "Lymphoma",
    category: "Blood Disorders",
    description: "Cancer that begins in infection-fighting cells of the immune system, called lymphocytes.",
    symptoms: ["Painless swollen lymph nodes", "Persistent fatigue", "Fever", "Night sweats", "Unexplained weight loss", "Itchy skin", "Shortness of breath"],
    causes: ["Mutations in lymphocytes", "Unknown why mutations occur"],
    prevention: ["No known prevention", "Treating infections promptly"],
    treatment: ["Chemotherapy", "Radiation therapy", "Targeted drugs", "Immunotherapy", "Bone marrow transplant"],
    riskFactors: ["Age", "Male sex", "Compromised immune system", "Certain infections", "Family history"],
    whenToSeeDoctor: "See a doctor if you have persistent signs and symptoms that concern you."
  },
  {
    id: "sickle-cell-disease",
    name: "Sickle Cell Disease",
    category: "Blood Disorders",
    description: "A group of inherited red blood cell disorders where red blood cells become misshapen and break down.",
    symptoms: ["Anemia", "Episodes of pain (crises)", "Swelling of hands and feet", "Frequent infections", "Delayed growth", "Vision problems"],
    causes: ["Inherited genetic mutation affecting hemoglobin"],
    prevention: ["Genetic counseling", "Prenatal testing"],
    treatment: ["Hydroxyurea", "Blood transfusions", "Pain medications", "Bone marrow transplant", "Preventing complications"],
    riskFactors: ["Both parents carrying the sickle cell gene", "African descent", "Mediterranean, Middle Eastern, Indian ancestry"],
    whenToSeeDoctor: "Seek emergency care for stroke symptoms, fever, unexplained episodes of severe pain, or swelling in abdomen."
  },
  {
    id: "thalassemia",
    name: "Thalassemia",
    category: "Blood Disorders",
    description: "An inherited blood disorder that causes your body to have less hemoglobin than normal.",
    symptoms: ["Fatigue", "Weakness", "Pale or yellowish skin", "Facial bone deformities", "Slow growth", "Abdominal swelling", "Dark urine"],
    causes: ["Inherited genetic mutations affecting hemoglobin production"],
    prevention: ["Genetic counseling", "Prenatal testing"],
    treatment: ["Blood transfusions", "Chelation therapy", "Bone marrow transplant", "Folic acid supplements"],
    riskFactors: ["Family history", "Mediterranean, South Asian, Southeast Asian, Middle Eastern, African ancestry"],
    whenToSeeDoctor: "See a doctor if your child has any symptoms of thalassemia."
  },

  // RENAL DISEASES
  {
    id: "kidney-stones",
    name: "Kidney Stones",
    category: "Renal",
    description: "Hard deposits made of minerals and salts that form inside the kidneys.",
    symptoms: ["Severe pain in side and back", "Pain radiating to lower abdomen", "Pain in waves", "Burning urination", "Pink or red urine", "Cloudy or foul-smelling urine", "Nausea and vomiting", "Frequent urination"],
    causes: ["Concentrated urine", "Dehydration", "Certain diets", "Obesity", "Digestive diseases", "Other medical conditions"],
    prevention: ["Drink plenty of water", "Eat fewer oxalate-rich foods", "Choose low-sodium diet", "Eat less animal protein", "Continue eating calcium-rich foods"],
    treatment: ["Pain relievers", "Alpha blockers", "Sound wave treatment (lithotripsy)", "Surgery for large stones", "Parathyroid gland surgery"],
    riskFactors: ["Family or personal history", "Dehydration", "Certain diets", "Obesity", "Digestive diseases", "Other conditions"],
    whenToSeeDoctor: "Seek immediate care if you have severe pain, blood in urine, difficulty urinating, or fever with chills."
  },
  {
    id: "glomerulonephritis",
    name: "Glomerulonephritis",
    category: "Renal",
    description: "Inflammation of the tiny filters in the kidneys (glomeruli) that can lead to kidney failure.",
    symptoms: ["Pink or cola-colored urine", "Foamy urine", "High blood pressure", "Fluid retention with swelling", "Fatigue"],
    causes: ["Infections", "Immune diseases", "Vasculitis", "Conditions that cause scarring"],
    prevention: ["Prompt treatment of strep infections", "Practice safe sex", "Avoid IV drug use", "Control high blood pressure and diabetes"],
    treatment: ["Treating underlying cause", "Blood pressure medications", "Diuretics", "Corticosteroids", "Dialysis", "Kidney transplant"],
    riskFactors: ["Family history", "Strep infections", "Lupus", "Hepatitis B or C", "HIV"],
    whenToSeeDoctor: "See a doctor if you notice blood in your urine or other signs of glomerulonephritis."
  },
  {
    id: "urinary-tract-infection",
    name: "Urinary Tract Infection (UTI)",
    category: "Renal",
    description: "An infection in any part of the urinary system — kidneys, ureters, bladder, and urethra.",
    symptoms: ["Strong urge to urinate", "Burning sensation when urinating", "Passing small amounts frequently", "Cloudy urine", "Red or pink urine", "Strong-smelling urine", "Pelvic pain"],
    causes: ["Bacteria entering urinary tract", "E. coli most common", "Sexual activity", "Certain birth control", "Urinary tract abnormalities"],
    prevention: ["Drink plenty of fluids", "Wipe front to back", "Empty bladder after intercourse", "Avoid irritating feminine products", "Change birth control method if causing infections"],
    treatment: ["Antibiotics", "Pain medications", "Increased fluid intake", "Heating pad for discomfort"],
    riskFactors: ["Female anatomy", "Sexual activity", "Certain birth control", "Menopause", "Urinary tract abnormalities", "Blockages", "Suppressed immune system", "Catheter use"],
    whenToSeeDoctor: "See a doctor if you have symptoms of a UTI, especially if you have fever or back pain."
  },
  {
    id: "polycystic-kidney-disease",
    name: "Polycystic Kidney Disease",
    category: "Renal",
    description: "A genetic disorder that causes numerous fluid-filled cysts to grow in the kidneys.",
    symptoms: ["High blood pressure", "Back or side pain", "Blood in urine", "Feeling of fullness in abdomen", "Increased abdomen size", "Headaches", "Kidney stones", "Kidney failure"],
    causes: ["Inherited genetic mutations", "Autosomal dominant (most common)", "Autosomal recessive"],
    prevention: ["No prevention", "Genetic testing for family planning"],
    treatment: ["Blood pressure management", "Pain management", "Dialysis", "Kidney transplant", "Treatment of complications"],
    riskFactors: ["Having a parent with the condition"],
    whenToSeeDoctor: "See a doctor if you have signs of polycystic kidney disease, especially if you have a family history."
  },

  // SKIN DISEASES
  {
    id: "eczema",
    name: "Eczema (Atopic Dermatitis)",
    category: "Dermatological",
    description: "A condition that makes skin red, inflamed, and itchy, common in children but can occur at any age.",
    symptoms: ["Dry skin", "Itching (severe at night)", "Red to brownish-gray patches", "Small raised bumps", "Thickened, cracked skin", "Raw, sensitive skin from scratching"],
    causes: ["Genetics", "Immune system dysfunction", "Environmental triggers", "Skin barrier dysfunction"],
    prevention: ["Moisturize regularly", "Avoid triggers", "Take shorter baths or showers", "Use gentle soaps", "Wear soft fabrics"],
    treatment: ["Moisturizers", "Corticosteroid creams", "Calcineurin inhibitors", "Antihistamines", "Light therapy", "Wet dressings"],
    riskFactors: ["Family history of eczema, allergies, or asthma", "Being a child"],
    whenToSeeDoctor: "See a doctor if eczema affects daily activities, causes sleep loss, or shows signs of infection."
  },
  {
    id: "acne",
    name: "Acne",
    category: "Dermatological",
    description: "A skin condition that occurs when hair follicles become plugged with oil and dead skin cells.",
    symptoms: ["Whiteheads", "Blackheads", "Small red tender bumps", "Pimples with pus", "Large painful lumps beneath skin", "Painful pus-filled lumps"],
    causes: ["Excess oil production", "Hair follicles clogged", "Bacteria", "Hormonal changes", "Certain medications", "Diet"],
    prevention: ["Wash face twice daily", "Use oil-free products", "Remove makeup before bed", "Avoid touching face", "Shower after activities that cause sweating"],
    treatment: ["Topical treatments (benzoyl peroxide, retinoids, antibiotics)", "Oral medications", "Therapies like light therapy or chemical peels"],
    riskFactors: ["Age (teenagers)", "Hormonal changes", "Family history", "Oily products", "Friction or pressure on skin"],
    whenToSeeDoctor: "See a doctor if self-care doesn't work, acne is severe, or if you're developing scars."
  },
  {
    id: "vitiligo",
    name: "Vitiligo",
    category: "Dermatological",
    description: "A disease that causes loss of skin color in patches when cells that produce melanin die or stop functioning.",
    symptoms: ["Patchy loss of skin color", "Premature whitening of hair", "Loss of color in mouth and nose tissues", "Change in eye color"],
    causes: ["Autoimmune condition", "Heredity", "Trigger event (sunburn, stress, chemical exposure)"],
    prevention: ["No known prevention", "Sun protection may help prevent spread"],
    treatment: ["Medications to restore color", "Light therapy", "Surgery", "Depigmentation therapy", "Cosmetics"],
    riskFactors: ["Family history", "Having another autoimmune condition"],
    whenToSeeDoctor: "See a doctor if areas of skin, hair, or eyes lose coloring."
  },
  {
    id: "rosacea",
    name: "Rosacea",
    category: "Dermatological",
    description: "A common skin condition that causes redness and visible blood vessels in the face.",
    symptoms: ["Facial redness", "Swollen red bumps", "Eye problems", "Enlarged nose", "Visible blood vessels", "Burning sensation"],
    causes: ["Unknown", "May involve blood vessels, immune system, microorganisms", "Heredity"],
    prevention: ["Identify and avoid triggers", "Protect face from sun and cold", "Handle face gently", "Reduce stress"],
    treatment: ["Topical drugs", "Oral antibiotics", "Laser therapy", "Other light therapies"],
    riskFactors: ["Being female", "Being over 30", "Smoking", "Family history", "Fair skin"],
    whenToSeeDoctor: "See a doctor if you experience persistent redness of your face."
  },
  {
    id: "shingles",
    name: "Shingles (Herpes Zoster)",
    category: "Dermatological",
    description: "A viral infection that causes a painful rash, caused by the same virus that causes chickenpox.",
    symptoms: ["Pain, burning, numbness", "Sensitivity to touch", "Red rash that appears after pain", "Fluid-filled blisters", "Itching", "Fever", "Headache", "Fatigue"],
    causes: ["Varicella-zoster virus reactivation", "Weakened immunity", "Aging", "Stress"],
    prevention: ["Shingles vaccine", "Chickenpox vaccine for those who haven't had chickenpox"],
    treatment: ["Antiviral medications", "Pain relievers", "Numbing agents", "Anticonvulsants", "Tricyclic antidepressants"],
    riskFactors: ["Age over 50", "Weakened immune system", "Cancer treatment", "Certain medications"],
    whenToSeeDoctor: "See a doctor if you suspect shingles, especially near the eye, if you're over 60, or if you have a weakened immune system."
  },
  {
    id: "melanoma",
    name: "Melanoma",
    category: "Dermatological",
    description: "The most serious type of skin cancer, develops in the cells that give skin its color.",
    symptoms: ["Change in existing mole", "Development of new pigmented growth", "Mole with irregular borders", "Mole with uneven coloring", "Mole that changes size or appearance"],
    causes: ["UV radiation exposure", "Genetic mutations in melanocytes"],
    prevention: ["Avoid sun during peak hours", "Wear sunscreen", "Wear protective clothing", "Avoid tanning beds", "Check skin regularly"],
    treatment: ["Surgery to remove melanoma", "Lymph node removal", "Immunotherapy", "Targeted therapy", "Radiation therapy", "Chemotherapy"],
    riskFactors: ["Fair skin", "History of sunburns", "Excessive UV exposure", "Living near equator", "Many moles", "Family history", "Weakened immune system"],
    whenToSeeDoctor: "See a doctor if you notice any changes in existing moles or new unusual growths."
  },

  // EYE DISEASES
  {
    id: "glaucoma",
    name: "Glaucoma",
    category: "Ophthalmological",
    description: "A group of eye conditions that damage the optic nerve, often caused by abnormally high pressure in the eye.",
    symptoms: ["Patchy blind spots", "Tunnel vision", "Severe headache", "Eye pain", "Nausea and vomiting", "Blurred vision", "Halos around lights"],
    causes: ["Elevated intraocular pressure", "Reduced blood flow to optic nerve", "Genetic factors"],
    prevention: ["Regular dilated eye exams", "Know family history", "Exercise safely", "Take prescribed eye drops", "Wear eye protection"],
    treatment: ["Eye drops", "Oral medications", "Laser treatment", "Surgery", "Combination of treatments"],
    riskFactors: ["High internal eye pressure", "Age over 60", "Black, Asian, or Hispanic heritage", "Family history", "Certain medical conditions", "Corticosteroid use"],
    whenToSeeDoctor: "Seek immediate care if you have severe headache, eye pain, nausea, or blurred vision."
  },
  {
    id: "cataracts",
    name: "Cataracts",
    category: "Ophthalmological",
    description: "A clouding of the normally clear lens of the eye, leading to decreased vision.",
    symptoms: ["Clouded or blurred vision", "Difficulty with vision at night", "Sensitivity to light and glare", "Seeing halos around lights", "Fading colors", "Double vision", "Frequent prescription changes"],
    causes: ["Aging", "Injury", "Previous eye surgery", "Medical conditions", "Long-term corticosteroid use"],
    prevention: ["Regular eye exams", "Quit smoking", "Manage health problems", "Eat fruits and vegetables", "Wear sunglasses", "Reduce alcohol use"],
    treatment: ["Stronger lighting and glasses initially", "Cataract surgery when vision impairment affects daily activities"],
    riskFactors: ["Aging", "Diabetes", "Excessive sunlight exposure", "Smoking", "Obesity", "High blood pressure", "Previous eye injury or surgery", "Prolonged corticosteroid use"],
    whenToSeeDoctor: "See an eye doctor if you notice changes in your vision."
  },
  {
    id: "macular-degeneration",
    name: "Age-Related Macular Degeneration",
    category: "Ophthalmological",
    description: "An eye disease that blurs the central vision due to damage to the macula.",
    symptoms: ["Visual distortions", "Reduced central vision", "Need for brighter light", "Difficulty adapting to low light", "Blurriness of printed words", "Decreased color intensity", "Difficulty recognizing faces"],
    causes: ["Exact cause unknown", "Combination of heredity and environmental factors"],
    prevention: ["Regular eye exams", "Manage other conditions", "Healthy diet rich in antioxidants", "Don't smoke", "Maintain healthy weight", "Exercise"],
    treatment: ["Anti-VEGF medications", "Laser therapy", "Photodynamic therapy", "Low vision rehabilitation"],
    riskFactors: ["Age over 50", "Family history", "Smoking", "Obesity", "Cardiovascular disease"],
    whenToSeeDoctor: "See an eye doctor if you notice changes in your central vision or your ability to see colors and fine detail."
  },
  {
    id: "diabetic-retinopathy",
    name: "Diabetic Retinopathy",
    category: "Ophthalmological",
    description: "A diabetes complication that affects eyes, caused by damage to blood vessels in the retina.",
    symptoms: ["Floaters", "Blurred vision", "Fluctuating vision", "Dark or empty areas in vision", "Vision loss"],
    causes: ["High blood sugar damages retinal blood vessels", "Blockage and leakage of blood vessels", "Abnormal new blood vessel growth"],
    prevention: ["Manage diabetes well", "Monitor blood sugar", "Control blood pressure and cholesterol", "Quit smoking", "Regular eye exams"],
    treatment: ["Laser treatment", "Vitrectomy", "Anti-VEGF injections", "Controlling diabetes"],
    riskFactors: ["Duration of diabetes", "Poor blood sugar control", "High blood pressure", "High cholesterol", "Pregnancy", "Tobacco use"],
    whenToSeeDoctor: "Have comprehensive eye exams regularly if you have diabetes, and immediately if vision changes suddenly."
  },
  {
    id: "conjunctivitis",
    name: "Conjunctivitis (Pink Eye)",
    category: "Ophthalmological",
    description: "Inflammation or infection of the transparent membrane that lines the eyelid and eyeball.",
    symptoms: ["Redness in eye", "Itchiness", "Gritty feeling", "Discharge that forms crust", "Tearing"],
    causes: ["Viruses", "Bacteria", "Allergies", "Chemical splash", "Foreign object", "Blocked tear duct (in newborns)"],
    prevention: ["Don't touch eyes", "Wash hands frequently", "Don't share personal items", "Use clean towels and washcloths", "Change pillowcases often"],
    treatment: ["Antibiotics for bacterial", "Antiviral for herpes simplex", "Antihistamines for allergies", "Artificial tears", "Cool compresses"],
    riskFactors: ["Exposure to infected person", "Exposure to allergens", "Contact lens use"],
    whenToSeeDoctor: "See a doctor if you have eye pain, light sensitivity, vision problems, or symptoms that worsen."
  },

  // ADDITIONAL COMMON CONDITIONS
  {
    id: "common-cold",
    name: "Common Cold",
    category: "Infectious",
    description: "A viral infection of your nose and throat (upper respiratory tract) that's usually harmless.",
    symptoms: ["Runny or stuffy nose", "Sore throat", "Cough", "Congestion", "Slight body aches", "Sneezing", "Low-grade fever", "Malaise"],
    causes: ["Many types of viruses (rhinoviruses most common)", "Spread through droplets or contaminated surfaces"],
    prevention: ["Wash hands frequently", "Avoid touching face", "Stay away from sick people", "Disinfect surfaces", "Keep immune system healthy"],
    treatment: ["Rest", "Fluids", "Over-the-counter cold remedies", "Pain relievers", "Decongestants", "Cough suppressants"],
    riskFactors: ["Age (children under 6)", "Weakened immune system", "Time of year (fall and winter)", "Exposure to crowds"],
    whenToSeeDoctor: "See a doctor if fever exceeds 101.3°F, symptoms last more than 10 days, or symptoms are severe or unusual."
  },
  {
    id: "sinusitis",
    name: "Sinusitis",
    category: "Respiratory",
    description: "Inflammation or swelling of the tissue lining the sinuses that can be acute or chronic.",
    symptoms: ["Facial pain or pressure", "Nasal congestion", "Thick nasal discharge", "Loss of smell", "Cough", "Fatigue", "Dental pain", "Bad breath"],
    causes: ["Viral infections", "Bacterial infections", "Allergies", "Nasal polyps", "Deviated septum"],
    prevention: ["Wash hands", "Avoid people with colds", "Manage allergies", "Avoid polluted air", "Use humidifier"],
    treatment: ["Nasal corticosteroids", "Saline nasal irrigation", "Decongestants", "Antibiotics for bacterial infection", "Allergy medications", "Surgery for chronic cases"],
    riskFactors: ["Allergies", "Nasal polyps", "Deviated septum", "Asthma", "Regular exposure to pollutants", "Immune system disorders"],
    whenToSeeDoctor: "See a doctor if symptoms last more than 10 days, you have a high fever, or symptoms recur frequently."
  },
  {
    id: "allergic-rhinitis",
    name: "Allergic Rhinitis (Hay Fever)",
    category: "Respiratory",
    description: "An allergic response causing itchy, watery eyes, sneezing, and other similar symptoms.",
    symptoms: ["Runny nose", "Sneezing", "Itchy eyes, nose, or roof of mouth", "Watery eyes", "Congestion", "Fatigue", "Cough", "Decreased sense of smell"],
    causes: ["Outdoor allergens (pollen)", "Indoor allergens (dust mites, pet dander)", "Irritants (cigarette smoke, perfume)"],
    prevention: ["Avoid allergens", "Keep windows closed during high pollen", "Use air conditioning", "Shower after being outdoors", "Keep home clean"],
    treatment: ["Antihistamines", "Decongestants", "Nasal corticosteroids", "Cromolyn sodium", "Leukotriene modifiers", "Immunotherapy"],
    riskFactors: ["Family history", "Having other allergies or asthma", "Having atopic dermatitis", "Exposure to cigarette smoke"],
    whenToSeeDoctor: "See a doctor if medications don't help, allergy symptoms are severe, or you have complications like sinus infections."
  },
  {
    id: "vertigo",
    name: "Vertigo",
    category: "Neurological",
    description: "A sensation of feeling off balance, often caused by inner ear problems.",
    symptoms: ["Spinning sensation", "Tilting", "Swaying", "Unbalanced feeling", "Pulled in one direction", "Nausea", "Vomiting", "Abnormal eye movements", "Headache"],
    causes: ["BPPV", "Meniere's disease", "Vestibular neuritis", "Head or neck injury", "Brain problems", "Migraine headaches"],
    prevention: ["Avoid sudden position changes", "Sit or lie down immediately when dizzy", "Avoid driving or operating machinery", "Reduce salt and caffeine"],
    treatment: ["Canalith repositioning", "Balance therapy", "Medications", "Surgery in severe cases"],
    riskFactors: ["Age", "Head injury", "Taking certain medications", "Prior episodes"],
    whenToSeeDoctor: "Seek immediate care for new severe headache, fever, double vision, difficulty speaking, or weakness."
  },
  {
    id: "carpal-tunnel",
    name: "Carpal Tunnel Syndrome",
    category: "Neurological",
    description: "A condition caused by a compressed nerve in the carpal tunnel, a narrow passageway on the palm side of your wrist.",
    symptoms: ["Tingling or numbness in fingers", "Hand weakness", "Dropping objects", "Shock-like sensations in fingers", "Pain radiating up arm"],
    causes: ["Compression of median nerve", "Wrist anatomy", "Certain health conditions", "Repetitive hand motions", "Pregnancy"],
    prevention: ["Reduce force and relax grip", "Take frequent breaks", "Watch hand form", "Improve posture", "Change computer mouse", "Keep hands warm"],
    treatment: ["Wrist splinting", "NSAIDs", "Corticosteroids", "Surgery to release pressure"],
    riskFactors: ["Female sex", "Obesity", "Wrist fracture or dislocation", "Rheumatoid arthritis", "Diabetes", "Thyroid disorders"],
    whenToSeeDoctor: "See a doctor if symptoms interfere with normal activities or sleep, or if there's persistent numbness or weakness."
  },
  {
    id: "chronic-fatigue",
    name: "Chronic Fatigue Syndrome",
    category: "Other",
    description: "A complicated disorder characterized by extreme fatigue that can't be explained by any underlying medical condition.",
    symptoms: ["Severe fatigue", "Memory or concentration problems", "Sore throat", "Enlarged lymph nodes", "Unexplained muscle or joint pain", "Headaches", "Unrefreshing sleep", "Extreme exhaustion after exercise"],
    causes: ["Unknown", "May involve viral infections", "Immune system problems", "Hormonal imbalances", "Stress"],
    prevention: ["No known prevention", "Stress management may help"],
    treatment: ["Managing symptoms", "Cognitive behavioral therapy", "Graded exercise therapy", "Sleep management", "Pain medications"],
    riskFactors: ["Age (40s-50s most common)", "Female sex", "Stress management difficulty"],
    whenToSeeDoctor: "See a doctor if you have persistent or excessive fatigue."
  },
  {
    id: "restless-leg",
    name: "Restless Legs Syndrome",
    category: "Neurological",
    description: "A condition that causes an uncontrollable urge to move the legs, usually due to uncomfortable sensations.",
    symptoms: ["Urge to move legs", "Sensations that begin at rest", "Relief with movement", "Worsening of symptoms in evening", "Nighttime leg twitching"],
    causes: ["Often unknown", "Genetics", "Iron deficiency", "Kidney failure", "Spinal cord conditions", "Certain medications"],
    prevention: ["No known prevention", "Managing underlying conditions may help"],
    treatment: ["Treating underlying condition", "Lifestyle changes", "Medications (dopamine agonists, anti-seizure drugs, opioids)", "Iron supplements"],
    riskFactors: ["Peripheral neuropathy", "Iron deficiency", "Kidney failure", "Spinal cord conditions", "Parkinson's disease"],
    whenToSeeDoctor: "See a doctor if symptoms affect your sleep or daily life."
  },
  {
    id: "bell-palsy",
    name: "Bell's Palsy",
    category: "Neurological",
    description: "A condition that causes temporary weakness or paralysis of the muscles on one side of the face.",
    symptoms: ["Sudden weakness on one side of face", "Facial droop", "Difficulty closing eye", "Drooling", "Pain around jaw or behind ear", "Decreased taste", "Sensitivity to sound"],
    causes: ["Viral infection (herpes simplex most common)", "Inflammation and swelling of facial nerve"],
    prevention: ["No known prevention"],
    treatment: ["Corticosteroids", "Antiviral drugs", "Physical therapy", "Eye protection", "Most cases improve without treatment"],
    riskFactors: ["Pregnancy", "Upper respiratory infections", "Diabetes"],
    whenToSeeDoctor: "See a doctor immediately if you have any type of facial paralysis to rule out stroke."
  },
  {
    id: "tinnitus",
    name: "Tinnitus",
    category: "Other",
    description: "The perception of noise or ringing in the ears when no external sound is present.",
    symptoms: ["Ringing", "Buzzing", "Roaring", "Clicking", "Hissing", "Humming"],
    causes: ["Age-related hearing loss", "Exposure to loud noise", "Earwax blockage", "Ear bone changes", "Meniere's disease", "TMJ disorders", "Neck injuries", "Certain medications"],
    prevention: ["Use hearing protection", "Turn down volume", "Take care of cardiovascular health", "Limit alcohol, caffeine, and nicotine"],
    treatment: ["Treating underlying cause", "White noise machines", "Hearing aids", "Masking devices", "Behavioral treatment", "Medications"],
    riskFactors: ["Loud noise exposure", "Age", "Male sex", "Tobacco and alcohol use", "Certain health problems"],
    whenToSeeDoctor: "See a doctor if tinnitus develops after upper respiratory infection, is accompanied by hearing loss or dizziness, or causes anxiety or depression."
  },
  {
    id: "hernia",
    name: "Hernia",
    category: "Gastrointestinal",
    description: "A condition that occurs when an organ pushes through an opening in the muscle or tissue that holds it in place.",
    symptoms: ["Bulge in affected area", "Pain or discomfort", "Weakness or pressure", "Burning or aching sensation", "Acid reflux", "Difficulty swallowing"],
    causes: ["Combination of muscle weakness and strain", "Heavy lifting", "Diarrhea or constipation", "Persistent coughing or sneezing"],
    prevention: ["Maintain healthy weight", "Eat high-fiber diet", "Lift heavy objects carefully", "Stop smoking", "Don't rely on trusses"],
    treatment: ["Watchful waiting", "Lifestyle changes", "Medications", "Surgery (open or laparoscopic)"],
    riskFactors: ["Being male", "Being older", "Being white", "Family history", "Chronic cough", "Chronic constipation", "Pregnancy", "Previous hernia"],
    whenToSeeDoctor: "Seek emergency care if hernia bulge becomes red, purple or dark, or if you have sudden pain, nausea, vomiting, or inability to have bowel movements."
  },
  {
    id: "appendicitis",
    name: "Appendicitis",
    category: "Gastrointestinal",
    description: "Inflammation of the appendix, a finger-shaped pouch that projects from the colon on the lower right side of the abdomen.",
    symptoms: ["Sudden pain beginning around navel and shifting to lower right abdomen", "Pain worsening with movement", "Nausea and vomiting", "Loss of appetite", "Low-grade fever", "Constipation or diarrhea", "Abdominal bloating"],
    causes: ["Blockage in appendix lining", "Infection causing appendix to swell"],
    prevention: ["No proven prevention", "High-fiber diet may help"],
    treatment: ["Appendectomy (surgical removal)", "Antibiotics before surgery"],
    riskFactors: ["Age (teens and 20s most common)", "Male sex", "Family history"],
    whenToSeeDoctor: "Seek immediate care if you have severe abdominal pain. A ruptured appendix is life-threatening."
  },
];

// Additional categories for the extended database
export const extendedDiseaseCategories = [
  "All",
  "Cardiovascular",
  "Respiratory",
  "Neurological",
  "Mental Health",
  "Autoimmune",
  "Metabolic",
  "Gastrointestinal",
  "Infectious",
  "Endocrine",
  "Musculoskeletal",
  "Renal",
  "Blood Disorders",
  "Dermatological",
  "Ophthalmological",
  "Other"
];
