interface ConditionData {
  name: string;
  probability?: string;
  likelihood?: string;
  description?: string;
  matchingSymptoms?: string[];
  relatedFindings?: string[];
  recommendations?: string[];
  urgency?: string;
}

interface ReportData {
  title: string;
  date: string;
  inputData?: string;
  conditions: ConditionData[];
  summary?: string;
  generalAdvice?: string;
  recommendations?: string[];
  disclaimer?: string;
}

export const generateReportText = (data: ReportData): string => {
  let text = `${"=".repeat(60)}\n`;
  text += `MEDICAL AI - ${data.title.toUpperCase()}\n`;
  text += `${"=".repeat(60)}\n\n`;
  text += `Date: ${data.date}\n\n`;

  if (data.inputData) {
    text += `INPUT DATA\n${"-".repeat(40)}\n`;
    text += `${data.inputData}\n\n`;
  }

  if (data.summary) {
    text += `SUMMARY\n${"-".repeat(40)}\n`;
    text += `${data.summary}\n\n`;
  }

  if (data.conditions && data.conditions.length > 0) {
    text += `POSSIBLE CONDITIONS\n${"-".repeat(40)}\n\n`;

    data.conditions.forEach((condition, index) => {
      const probability = condition.probability || condition.likelihood || "Unknown";
      const probabilityPercent = getProbabilityPercent(probability);
      
      text += `${index + 1}. ${condition.name}\n`;
      text += `   Probability: ${probability} (${probabilityPercent}%)\n`;
      
      if (condition.urgency) {
        text += `   Urgency: ${condition.urgency}\n`;
      }
      
      if (condition.description) {
        text += `   Description: ${condition.description}\n`;
      }

      if (condition.matchingSymptoms && condition.matchingSymptoms.length > 0) {
        text += `   Matching Symptoms: ${condition.matchingSymptoms.join(", ")}\n`;
      }

      if (condition.relatedFindings && condition.relatedFindings.length > 0) {
        text += `   Related Findings: ${condition.relatedFindings.join(", ")}\n`;
      }

      if (condition.recommendations && condition.recommendations.length > 0) {
        text += `   Recommendations:\n`;
        condition.recommendations.forEach((rec) => {
          text += `      - ${rec}\n`;
        });
      }

      text += `\n`;
    });
  }

  if (data.generalAdvice) {
    text += `GENERAL ADVICE\n${"-".repeat(40)}\n`;
    text += `${data.generalAdvice}\n\n`;
  }

  if (data.recommendations && data.recommendations.length > 0) {
    text += `RECOMMENDATIONS\n${"-".repeat(40)}\n`;
    data.recommendations.forEach((rec, index) => {
      text += `${index + 1}. ${rec}\n`;
    });
    text += `\n`;
  }

  text += `${"=".repeat(60)}\n`;
  text += `MEDICAL DISCLAIMER\n`;
  text += `${"=".repeat(60)}\n`;
  text += data.disclaimer || 
    "This analysis is for educational purposes only and should not be considered medical advice. Please consult a healthcare professional for proper diagnosis and treatment.";
  text += `\n\n`;
  text += `Generated by Medical AI on ${data.date}\n`;

  return text;
};

export const downloadReport = (data: ReportData) => {
  const text = generateReportText(data);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `medical-ai-report-${new Date().toISOString().split("T")[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const getProbabilityPercent = (probability: string): number => {
  switch (probability.toLowerCase()) {
    case "high":
      return 85;
    case "medium":
      return 60;
    case "low":
      return 35;
    case "very low":
      return 15;
    default:
      return 50;
  }
};

export const getProbabilityLabel = (probability: string): string => {
  const percent = getProbabilityPercent(probability);
  return `${percent}% match`;
};
