project_id = "affqqjllibazvolkjlad"

[functions.chat]
verify_jwt = false

[functions.analyze-symptoms]
verify_jwt = false

[functions.analyze-report]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false
