project_id = "pxrqkkejnmbartvpuwlx"

[auth]
site_url = "https://project-14snn.vercel.app"
additional_redirect_urls = [
  "http://localhost:5173/**",
  "https://project-14snn.vercel.app/**",
  "https://*-raiarchana258-9473s-projects.vercel.app/**",
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8

[auth.external.google]
enabled = true
client_id = "1050215806885-1i8q0kuu16k82v3matptl91u005rib8g.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false

[functions.chat]
verify_jwt = false

[functions.medical-chat]
verify_jwt = false

[functions.analyze-symptoms]
verify_jwt = false

[functions.analyze-report]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.send-medication-reminders]
verify_jwt = false
